### ISSUE TITLE
I'm getting this error during installation, any help? Please

### ISSUE THREAD

**Issue by LyviaSC77** [michael-franke/bayes_mixed_regression_tutorial#3]
Downloading GitHub repo michael-franke/bayes_mixed_regression_tutorial@HEAD
✓  checking for file ‘/private/var/folders/tx/g96y8lbx2wn1rjfrr2m_dxwr0000gn/T/RtmpQrwyh8/remotes87b66bfff57/michael-franke-bayes_mixed_regression_tutorial-74178c3/faintr/DESCRIPTION’ ...
─  preparing ‘faintr’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   WARNING: Removing directory ‘faintr/Meta’ which should only occur in an
     installed package
─  building ‘faintr_0.0.8.tar.gz’
   
* installing *source* package ‘faintr’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘HDInterval’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘faintr’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/faintr’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/tx/g96y8lbx2wn1rjfrr2m_dxwr0000gn/T//RtmpQrwyh8/file87b4714dd74/faintr_0.0.8.tar.gz’ had non-zero exit status

**Comment by michael-franke** [comment]
There is a problem with lazy load. See the line "there is no package called ‘HDInterval’” in the output.
 Try installing the package ‘HDInterval’ manually before installing ‘faintr’ with `install.packages(‘HDInterval’)`. Do that with any other package that the installation might complain about.
If you are using RStudio, try installing in a terminal.
